version: "3.9"

services:
  crud-php-cli:
    build:
      context: ./backend
      dockerfile: docker/php-cli/Dockerfile
    container_name: crud-php-cli
    volumes:
      - ./backend:/app
    depends_on:
      - crud-pgsql
    networks:
      - crud-test

  crud-php-fpm:
    build:
      context: ./backend
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - crud-pgsql
    networks:
      - crud-test

  crud-pgsql:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: crud
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crud_db
    container_name: crud-pgsql
    restart: unless-stopped
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - crud-test

  crud-api-nginx:
    build:
      context: ./backend
      dockerfile: docker/nginx/Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
    depends_on:
      - crud-php-fpm
      - crud-php-cli
    networks:
      - crud-test

networks:
  crud-test:
    driver: bridge

volumes:
  postgres-storage:
