doctrine:
    dbal:
        driver: 'pdo_pgsql'
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Quote:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Quote/Entities'
                prefix: 'App\Model\Quote\Entities'
                alias: Quote
